version: "3"
services:
  mysql:
    image: mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=veterinaria
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=1234
    volumes:
      - "veterinaria_bd:/var/lib/mysql:rw"
    networks:
      - mysql
  api-gateway:
    image: "anakin86708/veterinaria-api-gateway:0.0.1-SNAPSHOT"
    ports:
      - "8765:8765"
    restart: "no"
    depends_on:
      - naming-server
      - zipkin
    environment:
      - "EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka"
    networks:
      - default_network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: unless-stopped
    networks:
      - default_network

  naming-server:
    image: "anakin86708/veterinaria-naming-server:0.0.1-SNAPSHOT"
    ports:
      - "8761:8761"
    restart: "no"
    networks:
      - default_network
  user-service:
    image: "anakin86708/user-service:0.0.1-SNAPSHOT"
    ports:
      - "8600:8600"
    depends_on:
      - naming-server
      - mysql
    networks:
      - default_network
      - mysql
  especie-service:
    image: "anakin86708/especie-service:0.0.1-SNAPSHOT"
    expose:
      - "8400"
    restart: "no"
    deploy:
      replicas: 2
    depends_on:
      - api-gateway
      - naming-server
      - mysql
    environment:
      - "EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka"
    networks:
      - default_network
      - mysql

  veterinario-service:
    image: "anakin86708/veterinario-service:0.0.1-SNAPSHOT"
    expose:
      - "8500"
    restart: "no"
    deploy:
      replicas: 2
    depends_on:
      - api-gateway
      - naming-server
      - mysql
    environment:
      - "EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka"
    networks:
      - default_network
      - mysql

  animal-service:
    image: "anakin86708/animal-service:0.0.1-SNAPSHOT"
    expose:
      - "8100"
    restart: "no"
    deploy:
      replicas: 2
    depends_on:
      - api-gateway
      - naming-server
      - especie-service
      - mysql
    environment:
      - "EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka"
      - "CLIENTE_SERVICE_URL=http://cliente-service"
      - "ESPECIE_SERVICE_URL=http://especie-service"
    networks:
      - default_network
      - mysql

  cliente-service:
    image: "anakin86708/cliente-service:0.0.1-SNAPSHOT"
    expose:
      - "8200"
    restart: "no"
    depends_on:
      - api-gateway
      - naming-server
      - mysql
    environment:
      - "EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka"
    networks:
      - default_network
      - mysql

  consulta-service:
    image: "anakin86708/consulta-service:0.0.1-SNAPSHOT"
    expose:
      - "8300"
    restart: "no"
    depends_on:
      - api-gateway
      - naming-server
      - veterinario-service
      - animal-service
      - cliente-service
      - mysql
    environment:
      - "EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka"
      - "ANIMAL_SERVICE_URL=http://animal-service"
      - "VETERINARIO_SERVICE_URL=http://veterinario-service"
    networks:
      - default_network
      - mysql

volumes:
  veterinaria_bd:

networks:
  default_network:
  mysql:
